version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: randomPassword123
    ports:
      - 1433:1433
      - 1434:1434
    volumes:
      - mssqlsys:/var/opt/mssql
      - mssqlusr:/var/opt/sqlserver
volumes:
  mssqlsys:
  mssqlusr: